import { Theme, Logic } from "globals.slint";
import { Button } from "components/elements.slint";

export { Theme, Logic }

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    Rectangle {
        background: Theme.primary;
        VerticalLayout {
            padding: 10px;
            spacing: 10px;
            Text {
                text: "Counter: \{root.counter}";
                font-family: Theme.font-family;
                font-size: Theme.font-size-title-large;
                color: Theme.on-primary;
            }
            Button {
                text: "Notification";
                clicked => { 
                    Logic.notify("Coucou");
                }
            }
        }
    }
}
