export global Logic {
    callback notify(string);
}


export global Theme {
    in-out property <brush> primary-0 : #000000;
    in-out property <brush> primary-10 : #00201E;
    in-out property <brush> primary-40 : #006A65;
    in-out property <brush> primary-90 : #F2FFFC;
    in-out property <brush> primary-100 : #FFFFFF;

    in-out property <brush> secondary-0 : #000000;
    in-out property <brush> secondary-10 : #071F1D;
    in-out property <brush> secondary-40 : #4C6360;
    in-out property <brush> secondary-90 : #CEE8E4;
    in-out property <brush> secondary-100 : #FFFFFF;
    
    in-out property <string> font-family : "Roboto Mono" ;
    in-out property <length> font-size-display-large : 57px;
    in-out property <length> font-size-display-medium: 45px;
    in-out property <length> font-size-display-small : 36px;
    in-out property <length> font-size-headline-large : 32px;
    in-out property <length> font-size-headline-medium: 28px;
    in-out property <length> font-size-headline-small : 22px;
    in-out property <length> font-size-title-large : 22px;
    in-out property <length> font-size-title-medium: 16px;
    in-out property <length> font-size-title-small : 14px;
    in-out property <length> font-size-label-large : 14px;
    in-out property <length> font-size-label-medium: 12px;
    in-out property <length> font-size-label-small : 11px;
    in-out property <length> font-size-body-large : 16px;
    in-out property <length> font-size-body-medium: 14px;
    in-out property <length> font-size-body-small : 12px;
    
    out property <brush> primary : primary-40; 
    out property <brush> on-primary : primary-100; 
    out property <brush> primary-container : primary-90; 
    out property <brush> on-primary-container : primary-10; 

    out property <brush> secondary : secondary-40; 
    out property <brush> on-secondary : secondary-100; 
    out property <brush> secondary-container : secondary-90; 
    out property <brush> on-secondary-container : secondary-10; 
}