export global Theme {
    in-out property <brush> primary-0 : #000000;
    in-out property <brush> primary-10 : #00201E;
    in-out property <brush> primary-40 : #006A65;
    in-out property <brush> primary-90 : #F2FFFC;
    in-out property <brush> primary-100 : #FFFFFF;

    in-out property <brush> secondary-0 : #000000;
    in-out property <brush> secondary-10 : #071F1D;
    in-out property <brush> secondary-40 : #4C6360;
    in-out property <brush> secondary-90 : #CEE8E4;
    in-out property <brush> secondary-100 : #FFFFFF;
    
    in-out property <string> font-family : "Roboto" ;
    in-out property <int> font-size-display-large : 57;
    in-out property <int> font-size-display-medium: 45;
    in-out property <int> font-size-display-small : 36;
    in-out property <int> font-size-headline-large : 32;
    in-out property <int> font-size-headline-medium: 28;
    in-out property <int> font-size-headline-small : 22;
    in-out property <int> font-size-title-large : 22;
    in-out property <int> font-size-title-medium: 16;
    in-out property <int> font-size-title-small : 14;
    in-out property <int> font-size-label-large : 14;
    in-out property <int> font-size-label-medium: 12;
    in-out property <int> font-size-label-small : 11;
    in-out property <int> font-size-body-large : 16;
    in-out property <int> font-size-body-medium: 14;
    in-out property <int> font-size-body-small : 12;
    
    out property <brush> primary : primary-40; 
    out property <brush> on-primary : primary-100; 
    out property <brush> primary-container : primary-90; 
    out property <brush> on-primary-container : primary-10; 

    out property <brush> secondary : secondary-40; 
    out property <brush> on-secondary : secondary-100; 
    out property <brush> secondary-container : secondary-90; 
    out property <brush> on-secondary-container : secondary-10; 
}